### PR TITLE
To-do List :interactive list + add & remove 

### PR DESCRIPTION
**Pull request by andym80**
In this project, I could implement  add & remove from the list
I added some functionality to this application to make it interactive. 
The user will also be able to mark task completion by selecting the corresponding checkbox (or undo it by unchecking the checkbox). 
The updated tasks list will be stored in local storage.

All suggestions are welcome!     Thank you

### CODE REVIEW

**Review by sumairq — CHANGES_REQUESTED** [review]
### Hi @andym80 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR

## Required Changes ♻️
_Check the comments under the review._
- [ ] Please use the `Array.filter()` method to clear all the completed todos here as specified in the requirements. 
image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### 👉 -[Optional] In future please don't submit a pull request which contains hundred's of thousands of changes. As in this case you deleted the node_modules directory due to which the reviewers cannot make inline comments .  

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by bimbolabuari — COMMENTED** [review]
Hello @andym80 👋,

_This is an additional review as a result of the second opinion request_.

- As requested by the previous code reviewer, it had been specified to use the `array.filter()` method as a requirement.  Using the filter method is a better approach since splice() (mutable) modifies the array while filter() (immutable) creates a new array and does not modify the original one.

- Kindly implement the requested changes and submit for another review on your dashboard 👏

Keep rocking 🚀!

**Review by tresorsawasawa — CHANGES_REQUESTED** [review]
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @andym80
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

almost-there

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle:
- [ ] **I know your project works as you can delete the completed tasks. But as mentioned by the previous reviewer, kindly make sure you use the `Array.filter()` method to clear the `Completed tasks` since it is [one of the project's requirements](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m2_interactive_list.md#:~:text=Implement%20a%20function%20for%20the%20%22Clear%20all%20completed%22%20button%20(use%20filter()%20method).). Using the filter method is a better approach since `splice()` (mutable) modifies the array while `filter()` (immutable) creates a new array and does not modify the original one.
image**
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by HAMMAS-SALEEM — CHANGES_REQUESTED** [review]
# Required Changes :recycle:

### Hi @andym80 :recycle:, 

### Highlights :1st_place_medal:
:heavy_check_mark:  Good commit history
:heavy_check_mark: Linters are passing
:heavy_check_mark: Very professional README
:heavy_check_mark: Correct Github flow
:heavy_check_mark: Descriptive PR

Good job so far :+1:
There are some issues that you still need to work on to go to the next project but you are almost there! :+1:

Check the comments under the review.

- [x] Please use the Array.filter() method to clear all the completed todos here as requested by the previous reviewer.
- [x] Please ignore your node_modules folder by adding it inside your .gitignore file

## Optional suggestions
_**Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.**_

Cheers and Happy Coding

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

**_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._**

**Review by BenMukebo — APPROVED** [review]
### Hi @andym80 , 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 




## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


- [OPTIONAL] According to the project requirements, you should have created one new JavaScript file imported as a module that should contain methods related to the status updates (`completed`: `true` / `false`). Kindly address this 👨🏻‍🎨 

- [OPTIONAL] Kindly, it would be nice to add explicit steps for cloning your app, as this will be of help to non-technical users. You can put the steps to clone and run the project in a new Getting Started section under the project's description. This includes `git clone URL` , `cd..`,  `npm install` , `npm start` etc

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
